name: Delete Old ACR Manifests

on:
  workflow_dispatch:  # Trigger manually

permissions:
  id-token: write  # Required for Azure login
  contents: read   # Minimal permission for repository access

jobs:
  delete-acr-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      run: |
        echo "Installing Azure CLI..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version  # Confirm installation

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: 39ccf470-8b8a-414e-934f-277f7c6e7ba4
        tenant-id: 06698be3-7107-4e65-ac59-1967f7c7c43e
        subscription-id: 1fe9963c-1fe2-4dcc-83a7-b49978ffb277
        identity-type: userAssigned

    - name: Fetch and Delete Manifests
      run: |
        set -x  # Enable command tracing
        echo "Fetching manifests to delete..."
        ACR_NAME="trumiotest"
        REPO_NAME="hello-world"

        # List manifests and skip the latest 2
        MANIFESTS=$(az acr manifest list-metadata -r $ACR_NAME -n $REPO_NAME --orderby time_desc \
          --query "[?contains(join(',', tags), 'u')]" -o tsv | grep digest | awk -F '": "' '{print $2}' | sed 's/",$//' | awk 'NR>2')

        echo "Manifests to delete:"
        echo "$MANIFESTS"

        # Delete each manifest
        for DIGEST in $MANIFESTS; do
          echo "Deleting manifest: $DIGEST"
          az acr manifest delete -r $ACR_NAME -n "$REPO_NAME@$DIGEST" --yes --debug  # Adding debug
        done

